title: VRcollab Research Products
author: VRcollab Pte. Ltd.
logo: logo.png

execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/vrcollab/vrcollab.github.io
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
